export const SIDE_NAVIGATION_BAR_OPEN = "SIDE_NAVIGATION_BAR_OPEN";
export const SIDE_NAVIGATION_BAR_CLOSE = "SIDE_NAVIGATION_BAR_CLOSE";
export const UPDATE_APPBAR_TITLE = "UPDATE_APPBAR_TITLE";
export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
